version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "mirumitech-dev"
s3_bucket = "common-dev-sam-artifactstore"
s3_prefix = "mirumitech-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"dev\" \
"""
tags = "project=\"mirumitech\" env=\"dev\" IaC=\"cfn\""
confirm_changeset = false

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "mirumitech-prd"
s3_bucket = "common-prd-sam-artifactstore"
s3_prefix = "mirumitech-prd"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"prd\" \
"""
tags = "project=\"mirumitech\" env=\"prd\" IaC=\"cfn\""
confirm_changeset = false
