AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: backend for mirumi.tech


Parameters:
  ResourcePrefix:
    Type: String
    Default: mirumitech
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - prd
  AllowedClientOrigin:
    Type: String
  UnHashedApiKey:
    Type: String


Resources:
  FunctionsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/functions.yaml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        EnvironmentName: !Ref EnvironmentName
        AllowedClientOrigin: !Ref AllowedClientOrigin
        UnHashedApiKey: !Ref UnHashedApiKey

  BffStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/bff.yaml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        EnvironmentName: !Ref EnvironmentName
        # RestApisDomain: !GetAtt FunctionsStack.Outputs.RestApisDomain
        # RestApisStageName: !GetAtt FunctionsStack.Outputs.RestApisStageName
