AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: back-end for mirumi.tech


Parameters:
  ResourcePrefix:
    Type: String
    Default: mirumitech
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - prd
  ApiAllowOrigin:
    Type: String
  UnHashedApiKey:
    Type: String


Resources:
  FunctionsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/functions.yaml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        EnvironmentName: !Ref EnvironmentName
        ApiAllowOrigin: !Ref ApiAllowOrigin
        UnHashedApiKey: !Ref UnHashedApiKey

  BffStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/bff.yaml
      Parameters:
        ResourcePrefix: !Ref ResourcePrefix
        EnvironmentName: !Ref EnvironmentName
