AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: backend for frontend resources


Parameters:
  ResourcePrefix:
    Type: String
    Default: mirumitech
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - prd
  # RestApisDomain:
  #   Type: String
  # RestApisStageName:
  #   Type: String


Conditions:
  IsPrd: !Equals [!Ref EnvironmentName, prd]


Resources:
  StaticHostingBucket:
    Type: AWS::S3::Bucket
    Condition: IsPrd
    Properties:
      BucketName: !Sub ${ResourcePrefix}-${EnvironmentName}-static-hosting
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  LoggingBucket:
    Type: AWS::S3::Bucket
    Condition: IsPrd
    Properties:
      BucketName: !Sub ${ResourcePrefix}-${EnvironmentName}-logging
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  StaticHostingCloudFront:
    Type: AWS::CloudFront::Distribution
    Condition: IsPrd
    Properties:
      DistributionConfig:
        Aliases:
          - "mirumi.tech"
        CacheBehaviors:  # `/_nuxt/*`s
          - AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # https://go.aws/3ei9N4j
            Compress: true
            PathPattern: /_nuxt/*
            TargetOriginId: !Ref StaticHostingBucket
            ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /assets/404.html
        DefaultRootObject: index.html
        DefaultCacheBehavior:  # `index.html`s
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # https://go.aws/3ei9N4j
          Compress: true
          TargetOriginId: !Ref StaticHostingBucket
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Logging:
          Bucket: !GetAtt LoggingBucket.DomainName
          IncludeCookies: true
        Origins:
          - DomainName: !Sub ${StaticHostingBucket}.s3-website-ap-northeast-1.amazonaws.com
            Id: !Ref StaticHostingBucket
            CustomOriginConfig:  # for only s3-static-hosting
              OriginProtocolPolicy: http-only
            # S3OriginConfig:  # for only non-s3-static-hosting
            #   OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
            OriginCustomHeaders:
              - HeaderName: Referer
                HeaderValue: !GetAtt StaticHostingBucket.DomainName
        Restrictions:
          GeoRestriction: 
            RestrictionType: none
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:145943270736:certificate/cd9c6ffd-8733-403c-a856-665835f70a4d
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
  # API GW 用 CloudFront（Full SSG ができるようになったので使わなくなった）
  # RestApisCloudFront:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #           - GET
  #           - HEAD
  #           - OPTIONS
  #           - PUT
  #           - POST
  #           - PATCH
  #           - DELETE
  #         CachedMethods:
  #           - GET
  #           - HEAD
  #         CachePolicyId: !If [IsPrd, a46af3a5-45f7-4916-9868-2009322582fc, 38bfaa6b-f33a-4f5b-9859-b0a4fcbf0041]  # common-${env}-caching-optimized-and-more
  #         Compress: true
  #         ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd  # https://go.aws/3sJ7tqV
  #         TargetOriginId: !Ref RestApisStageName
  #         ViewerProtocolPolicy: https-only
  #       Enabled: true
  #       HttpVersion: http2
  #       Origins:
  #         - DomainName: !Ref RestApisDomain
  #           Id: !Ref RestApisStageName
  #           CustomOriginConfig:
  #             OriginProtocolPolicy: https-only
  #             OriginSSLProtocols: 
  #               - TLSv1.2
  #           OriginPath: !Sub
  #             - /${RestApisStageName}
  #             - RestApisStageName: !Ref RestApisStageName
  #       Restrictions:
  #         GeoRestriction: 
  #           RestrictionType: none

  # OriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Condition: IsPrd
  #   Properties: 
  #     CloudFrontOriginAccessIdentityConfig: 
  #       Comment: !Sub ${ResourcePrefix}-${EnvironmentName}-static-hosting

  StaticSiteHostingPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: IsPrd
    Properties: 
      Bucket: !Ref StaticHostingBucket
      PolicyDocument: 
        {
          "Version": "2012-10-17",
          "Id": "StaticSiteHostingPublicReadPolicy",
          "Statement": [
            {
              "Sid": "StaticSiteHostingPublicReadPolicy",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": !Sub "arn:aws:s3:::${StaticHostingBucket}/*",
              "Condition": {
                "StringLike": {
                  "aws:Referer": [
                    !GetAtt StaticHostingBucket.DomainName
                  ]
                }
              }
            }
          ]
        }

  # OAIBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Condition: IsPrd
  #   Properties: 
  #     Bucket: !Ref StaticHostingBucket
  #     PolicyDocument: 
  #       {
  #         "Id": "OAIBucketPolicy",
  #         "Version": "2012-10-17",
  #         "Statement": [
  #           {
  #             "Sid": "OAIBucketPolicy",
  #             "Effect": "Allow",
  #             "Principal": {
  #               "AWS": !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}"
  #             },
  #             "Action": "s3:GetObject",
  #             "Resource": !Sub "arn:aws:s3:::${StaticHostingBucket}/*"
  #           }
  #         ]
  #       }
